language: node_js
services:
  - docker
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
after_success:
  - docker tag udagram-api-feed pelu2002/udagram-api-feed:v3
  - docker tag udagram-api-user pelu2002/udagram-api-user:v3
  - docker tag udagram-frontend pelu2002/udagram-frontend:v3
  - docker tag udagram-reverseproxy pelu2002/udagram-reverseproxy:v3

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pelu2002/udagram-api-feed:v3
  - docker push pelu2002/udagram-api-user:v3
  - docker push pelu2002/udagram-frontend:v3
  - docker push pelu2002/udagram-reverseproxy:v3