# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy

# Tagging
- docker tag udagram-api-feed kioluwapelumi/udagram-api-feed:v1
- docker tag udagram-api-user kioluwapelumi/udagram-api-user :v1
- docker tag udagram-frontend kioluwapelumi/udagram-frontend:v1
- docker tag udagram-reverseproxy kioluwapelumi/udagram-reverseproxy:v1
# Do similar for other three images

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push kioluwapelumi/udagram-api-feed:v1
- docker push kioluwapelumi/udagram-api-user:v1
- docker push kioluwapelumi/udagram-frontend:v1
- docker push kioluwapelumi/udagram-reverseproxy:v1